[package]
name = "chazzr"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "application"
path = "src/application/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
